import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>First Next App | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Home Page</h1>
      <div className={inter.className}>Hello Users!!</div>
      <p className={styles.text}>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ratione ipsum
        ullam tempore. Cum labore quaerat nulla ex laboriosam laborum eveniet
        aperiam quas amet ut a, obcaecati nam, consectetur adipisci qui.
      </p>
    </>
  );
}
